name: Half-Hourly Update Best IPs

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  update-best-ips:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Clean IPs
        run: |
          mkdir -p bestcf
          curl -sL "https://raw.githubusercontent.com/HandsomeMJZ/cfip/main/best_ips.txt" | \
          awk '{print $1}' > bestcf/best_ips.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add bestcf/best_ips.txt
          
          if ! git diff --staged --quiet; then
            git commit -m "Auto update best_ips: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
